Implement I and R-Type ALU instructions
Arka-Mondal/riscvemu pull request #1
Opened 2024-02-17 19:52 UTC by virinci

2024-02-19 19:32 UTC, Arka-Mondal requested changes
Added comments need attention.

2024-02-19 19:32 UTC, Arka-Mondal commented on src/cpu.c
> +              cpu->registers[rd] = (int64_t) (int32_t) ((uint32_t) cpu->registers[rs1] + (uint32_t) cpu->registers[rs2]);
@virinci may here and in ***line no: 378*** be `& 0xffffffff` will be better, just like you did with `ADDIW`.

2024-02-19 19:32 UTC, Arka-Mondal commented on src/cpu.c
> +              cpu->registers[rd] = (int64_t) cpu->registers[rs1] >> (int64_t) (cpu->registers[rs2] & 0x1f);
@virinci shouldn't it be `0x3f` instead of `0x1f` as 
> SLL, SRL, and SRA perform logical left, logical right, and arithmetic right shifts on the value in register rs1 by the shift amount held in register rs2. **In RV64I, only the low 6 bits of rs2 are considered for the shift amount**.

2024-02-19 19:32 UTC, Arka-Mondal commented on src/cpu.c
> +              uint64_t shift = cpu->registers[rs2] & 0x3f;
@virinci shouldn't it be `0x1f` instead of `0x3f` as 
> SLLW, SRLW, and SRAW are RV64I-only instructions that are analogously defined but operate on 32-bit values and produce signed 32-bit results. The shift amount is given by rs2[4:0].

2024-02-19 19:32 UTC, Arka-Mondal commented on src/cpu.c
> +              if (shift >> 5 & 1) {
@virinci if it is `0x1f` then I think there is no need of `(shift >> 5 & 1)`.

2024-02-19 19:32 UTC, Arka-Mondal commented on src/cpu.c
> +              uint64_t shift = cpu->registers[rs2] & 0x3f;
@virinci same here and in **line no. 414** shouldn't it be `0x1f` instead of `0x3f` as 
> SLLW, SRLW, and SRAW are RV64I-only instructions that are analogously defined but operate on 32-bit values and produce signed 32-bit results. The shift amount is given by rs2[4:0].

2024-02-20 03:42 UTC, virinci commented on src/cpu.c
> +              cpu->registers[rd] = (int64_t) cpu->registers[rs1] >> (int64_t) (cpu->registers[rs2] & 0x1f);
Yes

2024-02-20 03:46 UTC, virinci commented on src/cpu.c
> +              uint64_t shift = cpu->registers[rs2] & 0x3f;
`imm[5] != 0` case is reserved. So, it would be better to check if it's `0` and only then perform the shift operations.
> Previously, SLLIW, SRLIW, and SRAIW with imm[5] ̸= 0 were defined to cause illegal instruction exceptions, whereas now they are marked as reserved. This is a backwards-compatible change.

2024-02-20 03:49 UTC, virinci commented on src/cpu.c
> +              uint64_t shift = cpu->registers[rs2] & 0x3f;
Nevermind, that's for the immediate variant of the instructions.

2024-02-20 03:54 UTC, virinci commented on src/cpu.c
> +            case 0x20: // SRAI
Yes

2024-02-20 04:36 UTC, virinci commented on src/cpu.c
> +              cpu->registers[rd] = (int64_t) (int32_t) ((uint32_t) cpu->registers[rs1] + (uint32_t) cpu->registers[rs2]);
`uint32_t` will wrap on overflow, but sure :+1:

2024-02-20 04:47 UTC, virinci commented on src/cpu.c
> +            case 0x20: // SRAIW
I will change it to shift by 5 bits. The reserved case can be handled by the default case.

2024-02-20 04:58 UTC, virinci commented
@Arka-Mondal Please review the changes in the new commit.

2024-02-20 17:07 UTC, merged